// GENERATED by e2e-harness from assets/templates/playwright.config.ts.
// Values come from `playwright` in e2e/config.json. Edit there, then `e2e build`.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests/generated',
  // E2E journeys share real infrastructure -- topics, buckets, databases. Running
  // them in parallel makes them interfere, so serial is the honest default.
  workers: __WORKERS__,
  // Retries hide real flakiness. Prefer fixing the await_* step that is racing.
  retries: __RETRIES__,
  timeout: __TIMEOUT__,
  reporter: [['json'], ['line']],
  use: {
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
});
