// Lint <ddd-dir>/07-define/define.json and render the DEFINE Markdown artifacts from it.
//
//   ddd define render [ddd-dir] [--context ID ...] [--check-only] [--force] [--no-glossary]
//
// A line-for-line port of render.py. define.json is the chain; the Markdown is a faithful
// rendering of it plus upstream facts, so the two can never disagree. Renders:
//   07-define/<context>/bounded-context-canvas.md   Bounded Context Canvas v5 layout, one per canvas
//   07-define/system-context.md                     C4 L1 context (mermaid C4Context) + quality attributes
//   glossary.md                                     per-context sections regenerated; '## Shared' kept verbatim
//
// The lint refuses to render while judgement fields still hold TODO / "[draft ...]" markers
// or while a core context has no quality attribute, so an auto-mode run cannot ship an
// unfinished canvas. Files that lost their "generated by ddd-define" marker are treated as
// hand-edited and skipped unless --force (design invariant 4). Rendering never touches
// define.json or any other step JSON (invariant 3). The .prefill/ briefs are removed only
// after a full render, never on --check-only, never on --context (invariant 7).
//
// Exit 0 = rendered, 1 = lint errors; a missing define.json also exits 1 with the message
// on stderr, exactly as sys.exit("...") did (the goldens pin that). The Python-era hint
// wording (`run prefill.py --write first`, the marker naming render.py) is kept verbatim
// until leaf 1.4.1 rewords code and goldens together. Zero dependencies, ESM, Node >= 18.
import fs from "node:fs";
import path from "node:path";
import { ExitError, now } from "../../../shared/lib/manifest.mjs";
import {
  PATTERNS, UsageError, buildFacts, get, isDict, isTodo, lintC4, loadWorkspace, or, parseArgs, parseGlossary,
  partyIndex, plen, pyjoin, pyrepr, pyrstrip, pyslice, pystr, pystrip, sortedUnique, splitlines, termKey, truthy,
} from "./prefill.mjs";

const MARK = "generated by ddd define render";
// Files written before the Node cut-over carry the Python-era marker; they are still ours.
const LEGACY_MARK = "generated by ddd-define/scripts/render.py";
const hasMark = (s) => s.includes(MARK) || s.includes(LEGACY_MARK);
const DOMAIN_ROLES = new Set(["specification-model", "execution-context", "audit-model", "approver", "enforcer", "octopus",
  "interchange-context", "gateway", "analysis-context", "bubble-context", "autonomous-bubble",
  "brain", "funnel", "engagement-context", "other"]);
const BUSINESS_MODELS = new Set(["revenue-generator", "engagement-creator", "compliance-enforcer", "cost-reducer"]);
const DOMAINS = new Set(["core", "supporting", "generic"]);
const PRIORITY_RANK = { high: 0, medium: 1, low: 2 };

function cell(s) {
  return pystr(s === null || s === undefined ? "—" : s).split("|").join("\\|").split("\n").join(" ");
}

function firstSentence(s, n = 160) {
  s = pystrip(or(s, ""));
  const m = s.match(/^([^\n]+?[.!?])(\s|$)/);
  s = m ? m[1] : s;
  return plen(s) <= n ? s : pyslice(s, n - 1) + "…";
}

// ---------------------------------------------------------------- lint
function lint(ws, define, facts, parties, only = null) {
  const errors = [], warnings = [];
  const E = (s) => errors.push(s), W = (s) => warnings.push(s);
  for (const k of ["schema_version", "step", "produced_by", "produced_at", "mode", "depth", "inputs", "assumptions", "open_questions", "canvases", "quality_attributes"]) {
    if (!(k in define)) E(`envelope: missing '${k}'`);
  }
  if (get(define, "step") !== "define") E("envelope: step must be 'define'");
  if (!pystr(get(define, "system_context_c4_mermaid", "")).replace(/^\s+/, "").startsWith("C4Context")) E("system_context_c4_mermaid must start with 'C4Context'");
  if (get(define, "mode") === "auto" && !truthy(get(define, "assumptions"))) W("auto mode with zero envelope assumptions — every guess must be logged (modes.md §3)");
  const knownMsgs = new Set();
  let knownCmds = new Set();
  const S = ws.steps;
  if ("connect" in S) for (const m of get(S.connect, "messages", [])) knownMsgs.add(get(m, "id"));
  if ("discover" in S) {
    knownCmds = new Set(get(S.discover, "commands", []).map((c) => get(c, "id")));
    for (const e of get(S.discover, "events", [])) knownMsgs.add(get(e, "id"));
    for (const c of knownCmds) knownMsgs.add(c);
  }
  const contexts = [...facts.keys()];
  const seen = new Set();
  const coreCtx = new Set(contexts.filter((X) => facts.get(X).classification.domain === "core"));
  const qaByCtx = new Map();
  for (const q of get(define, "quality_attributes", [])) {
    const ctx = get(q, "context");
    if (!qaByCtx.has(ctx)) qaByCtx.set(ctx, []);
    qaByCtx.get(ctx).push(q);
    const qtag = `quality_attributes[${pystr(ctx)}/${pystr(get(q, "attribute"))}]`;
    for (const k of ["context", "attribute", "requirement", "priority"]) {
      if (!truthy(get(q, k))) E(`${qtag}: missing '${k}'`);
    }
    if (!["high", "medium", "low"].includes(get(q, "priority"))) E(`${qtag}: priority must be high|medium|low`);
    if (!contexts.includes(ctx) && ctx !== "system") W(`quality_attributes: unknown context '${pystr(ctx)}'`);
    if (!truthy(get(q, "scenario"))) W(`${qtag}: no scenario — a quality attribute without a concrete scenario is a wish, not a requirement`);
  }
  for (const c of get(define, "canvases", [])) {
    const X = get(c, "context");
    const tag = `canvas[${pystr(X)}]`;
    if (seen.has(X)) E(`${tag}: duplicate canvas`);
    seen.add(X);
    if (!contexts.includes(X)) {
      E(`${tag}: not a bounded context in decompose.json (known: ${pyrepr(contexts)})`);
      continue;
    }
    if (only && !only.has(X)) continue;
    for (const k of ["context", "purpose", "strategic_classification", "domain_roles", "inbound", "outbound", "ubiquitous_language", "business_decisions", "canvas_path"]) {
      if (!(k in c)) E(`${tag}: missing required key '${k}'`);
    }
    const p = pystr(get(c, "purpose", ""));
    if (isTodo(p)) E(`${tag}: purpose still a TODO/draft`);
    else if (plen(p) < 40) E(`${tag}: purpose is too short (${plen(p)} chars) — 2–4 sentences in business language`);
    else if (plen(p) > 1200) W(`${tag}: purpose is long (${plen(p)} chars) — a purpose is not a feature list`);
    const sc = or(get(c, "strategic_classification"), {});
    const fdom = facts.get(X).classification.domain;
    if (!DOMAINS.has(get(sc, "domain"))) E(`${tag}: strategic_classification.domain must be core|supporting|generic`);
    else if (truthy(fdom) && get(sc, "domain") !== fdom) W(`${tag}: domain '${pystr(get(sc, "domain"))}' differs from strategize (${fdom}) — ddd validate will warn`);
    if (!BUSINESS_MODELS.has(get(sc, "business_model"))) E(`${tag}: strategic_classification.business_model must be one of ${pyrepr(sortedUnique(BUSINESS_MODELS))}`);
    if (truthy(get(sc, "evolution")) && !["genesis", "custom", "product", "commodity"].includes(get(sc, "evolution"))) E(`${tag}: strategic_classification.evolution must be genesis|custom|product|commodity`);
    const roles = or(get(c, "domain_roles"), []);
    if (!truthy(roles)) E(`${tag}: domain_roles is empty — pick 1–2 from references/domain-roles.md`);
    for (const r of roles) {
      if (!DOMAIN_ROLES.has(r)) E(`${tag}: domain role '${pystr(r)}' is not in the contract enum ${pyrepr(sortedUnique(DOMAIN_ROLES))}`);
    }
    if (roles.length > 3) W(`${tag}: ${roles.length} domain roles — more than two usually means the context has several responsibilities`);
    if (!truthy(get(c, "domain_roles_rationale")) || isTodo(get(c, "domain_roles_rationale"))) E(`${tag}: domain_roles_rationale missing or TODO — say why the role fits (one or two sentences)`);
    const bd = or(get(c, "business_decisions"), []);
    if (!truthy(bd)) E(`${tag}: business_decisions is empty — every context decides something; write the rules/invariants`);
    for (const d of bd) if (isTodo(d)) E(`${tag}: business decision still a TODO/draft: ${pyslice(d, 80)}`);
    const vm = or(get(c, "verification_metrics"), []);
    if (!truthy(vm)) E(`${tag}: verification_metrics is empty — how would you know this context is healthy and its boundary right?`);
    for (const m of vm) if (isTodo(m)) E(`${tag}: verification metric still a TODO: ${pyslice(m, 80)}`);
    const keys = new Map();
    for (const t of or(get(c, "ubiquitous_language"), [])) {
      const d = pystr(or(get(t, "definition"), ""));
      if (isTodo(d) || !d) E(`${tag}: term '${pystr(get(t, "term"))}' has no definition`);
      else if (d.toLowerCase().includes("aggregate candidate")) E(`${tag}: term '${pystr(get(t, "term"))}' is described as an aggregate candidate, not defined — say what it IS in this context`);
      const k = termKey(get(t, "term"));
      if (keys.has(k)) E(`${tag}: terms '${pystr(keys.get(k))}' and '${pystr(get(t, "term"))}' are the same word — one meaning per term per context: merge or rename`);
      else keys.set(k, get(t, "term"));
    }
    for (const r of or(get(c, "read_models"), [])) {
      if (!isDict(r) || !truthy(get(r, "name"))) E(`${tag}: read_models entries are objects {name, informs, note} — '${pystr(r)}' has no name`);
      else if (truthy(get(r, "informs")) && knownCmds.size && !knownCmds.has(r.informs)) W(`${tag}: read model '${pystr(r.name)}' informs '${pystr(r.informs)}', which is not a discover command id`);
    }
    for (const a of or(get(c, "assumptions"), [])) if (isTodo(a)) E(`${tag}: assumption still a TODO: ${pyslice(a, 80)}`);
    for (const q of or(get(c, "open_questions"), [])) if (isTodo(q)) E(`${tag}: open question still a TODO: ${pyslice(q, 80)}`);
    for (const side of ["inbound", "outbound"]) {
      for (const coll of or(get(c, side), [])) {
        const collab = get(coll, "collaborator");
        if (!truthy(collab)) E(`${tag}.${side}: collaborator missing`);
        const rel = get(coll, "relationship");
        if (rel === "unspecified") W(`${tag}.${side}[${pystr(collab)}]: relationship unspecified — name the context-map pattern`);
        else if (truthy(rel) && !PATTERNS.has(rel) && rel !== "user-interaction" && rel !== "external-system") W(`${tag}.${side}[${pystr(collab)}]: relationship '${pystr(rel)}' is not a context-mapping pattern`);
        for (const m of or(get(coll, "messages"), [])) {
          if (get(m, "kind") === "response") E(`${tag}.${side}[${pystr(collab)}]: '${pystr(get(m, "id"))}' has kind 'response' — a response is not a row; put it on its request message as \`response: {id, payload}\``);
          else if (!["command", "event", "query"].includes(get(m, "kind"))) E(`${tag}.${side}[${pystr(collab)}]: message '${pystr(get(m, "id"))}' kind must be command|event|query`);
          if (knownMsgs.size && !knownMsgs.has(get(m, "id"))) E(`${tag}.${side}[${pystr(collab)}]: message id '${pystr(get(m, "id"))}' is not in connect.json or discover.json`);
        }
      }
    }
    const expected = `${ws.rel}/07-define/${X}/bounded-context-canvas.md`;
    if (get(c, "canvas_path") !== expected) E(`${tag}: canvas_path must be exactly '${expected}' (got '${pystr(get(c, "canvas_path"))}')`);
    if (coreCtx.has(X) && !truthy(qaByCtx.get(X))) E(`${tag}: core context has no quality attribute — run the light quality storming (references/quality-storming.md)`);
    if (get(define, "depth") === "deep" && !truthy(qaByCtx.get(X))) W(`${tag}: depth=deep but no quality attributes for this context`);
    else if (get(define, "depth") === "standard" && !coreCtx.has(X) && !truthy(qaByCtx.get(X))) {
      const f = facts.get(X);
      const ext = sortedUnique([...f.inbound, ...f.outbound].filter((e) => ["external", "system-actor"].includes(get(e, "collaborator_kind"))).map((e) => e.collaborator));
      if (ext.length) W(`${tag}: ${pystr(get(sc, "domain"))} context with external partner(s) ${pyrepr(ext)} and no quality attribute — one row (availability/idempotency/timeout) when the partner is on the critical path`);
    }
  }
  for (const X of contexts) if (!seen.has(X)) E(`no canvas for bounded context '${X}' — one canvas per context is required`);
  const c4 = pystr(get(define, "system_context_c4_mermaid", ""));
  const [c4e, c4w] = lintC4(c4);
  for (const e of c4e) E(`system_context_c4_mermaid: ${e}`);
  for (const w of c4w) W(`system_context_c4_mermaid: ${w}`);
  for (const c of get(define, "canvases", [])) {
    const f = facts.get(get(c, "context"));
    if (!truthy(f)) continue;
    for (const side of ["inbound", "outbound"]) {
      for (const coll of or(get(c, side), [])) {
        const pid = get(coll, "collaborator");
        const kind = or([...f.inbound, ...f.outbound].find((e) => e.collaborator === pid)?.collaborator_kind ?? null, get(or(parties.get(pid), {}), "kind"));
        if (kind === null) W(`canvas[${pystr(get(c, "context"))}].${side}: collaborator '${pystr(pid)}' is not a known context, actor or external system`);
        if (["actor", "external", "system-actor"].includes(kind) && !c4.includes(pystr(pid).replace(/[^A-Za-z0-9_]/g, "_"))) {
          W(`canvas[${pystr(get(c, "context"))}].${side}: collaborator '${pystr(pid)}' is not in system_context_c4_mermaid — add a Person/System_Ext + Rel line`);
        }
      }
    }
  }
  return [errors, warnings];
}

// ---------------------------------------------------------------- render canvas
const KIND_LABEL = { context: "bounded context", external: "external system", actor: "person", "system-actor": "external system" };

function pname(f, parties, pid) {
  for (const e of [...f.inbound, ...f.outbound]) if (e.collaborator === pid) return or(get(e, "collaborator_name"), pid);
  return or(get(or(parties.get(pid), {}), "name"), pid);
}

function pkind(f, parties, pid) {
  for (const e of [...f.inbound, ...f.outbound]) if (e.collaborator === pid) return KIND_LABEL[get(e, "collaborator_kind")] ?? "—";
  return KIND_LABEL[get(or(parties.get(pid), {}), "kind")] ?? "unknown party";
}

function mname(facts, mid) {
  for (const f of facts.values()) {
    for (const e of [...f.inbound, ...f.outbound]) for (const m of e.messages) if (m.id === mid) return get(m, "name", mid);
  }
  return mid;
}

function via(m) {
  const bits = [];
  if (truthy(get(m, "via"))) bits.push(pystr(m.via));
  if (get(m, "sync") === true) bits.push("sync");
  else if (get(m, "sync") === false) bits.push("async");
  if (truthy(get(m, "delivery")) && get(m, "delivery") !== "sync") bits.push(pystr(m.delivery));
  return or(bits.join(", "), "—");
}

// Payload cell; a folded response ('response': {id, payload}) is shown on the same row, never as its own.
function payload(m) {
  let s = or(or(get(m, "payload", []), []).join(", "), "—");
  const r = get(m, "response");
  if (isDict(r) && (truthy(get(r, "id")) || truthy(get(r, "payload")))) {
    s += `; response: \`${pystr(get(r, "id"))}\`` + (truthy(get(r, "payload")) ? ` (${r.payload.join(", ")})` : "");
  } else if (typeof r === "string" && r) {
    s += `; response: ${r}`;
  }
  return s;
}

function readModel(r) {
  const bits = [];
  if (truthy(get(r, "id"))) bits.push(`\`${pystr(r.id)}\``);
  if (truthy(get(r, "informs"))) bits.push(`informs \`${pystr(r.informs)}\``);
  if (truthy(get(r, "used_by"))) bits.push(`used by ${pystr(r.used_by)}`);
  if (truthy(get(r, "note"))) bits.push(pystr(r.note));
  return `**${pystr(r.name)}**` + (bits.length ? ` (${bits.join(", ")})` : "");
}

function renderCanvas(ws, define, facts, parties, c) {
  const X = c.context;
  const f = facts.get(X);
  const name = or(get(c, "name"), f.name);
  const team = or(f.team, {}), dep = or(f.deployable, {});
  const cl = f.classification;
  const sc = get(c, "strategic_classification", {});
  const L = [];
  const P = (s) => L.push(s);
  P(`# Bounded Context Canvas — ${pystr(name)}`);
  P("");
  P(`<!-- ${MARK} from ${ws.rel}/07-define/define.json on ${now()}. Edit define.json and re-render; delete this line to protect hand edits. -->`);
  P("");
  P("| | |");
  P("|---|---|");
  P(`| **Context id** | \`${X}\` |`);
  P(`| **Owning team** | ${cell(get(team, "name"))} (\`${pystr(get(team, "id", "—"))}\`, ${pystr(get(team, "type", "—"))}) |`);
  const others = get(dep, "contexts", []).filter((x) => x !== X);
  P(`| **Deployable** | ${cell(get(dep, "name"))} (\`${pystr(get(dep, "id", "—"))}\`, ${pystr(get(dep, "kind", "—"))}, data store: ${pystr(get(dep, "data_store", "—"))}${others.length ? "; shared with " + others.map((o) => "`" + o + "`").join(", ") : ""}) |`);
  P(`| **Subdomains** | ${or(f.subdomains.map((s) => "`" + s.id + "`").join(", "), "—")} |`);
  P(`| **Implementation pattern** | ${or(cl.implementation_pattern.join("/"), "—")} (sourcing: ${or(cl.sourcing.join("/"), "—")}, investment: ${or(cl.investment.join("/"), "—")}) |`);
  P(`| **Aggregates (candidates)** | ${or(f.owns_aggregates.map((a) => "`" + a.id + "`").join(", "), "— (not a domain model)")} |`);
  P("");
  P("## Purpose");
  P("");
  P(pystr(get(c, "purpose", "")));
  P("");
  P("## Strategic classification");
  P("");
  P("| Domain | Business model | Evolution |");
  P("|---|---|---|");
  P(`| ${pystr(get(sc, "domain", "—"))} | ${pystr(get(sc, "business_model", "—"))} | ${or(get(sc, "evolution"), cl.evolution, "—")} |`);
  if (truthy(cl.rationale)) {
    P("");
    P(`_Strategize rationale_: ${cl.rationale.map(pystr).join(" | ")}` + (truthy(cl.future_direction) ? ` — _future_: ${cl.future_direction.map(pystr).join(" | ")}` : ""));
  }
  P("");
  P("## Domain roles");
  P("");
  P(get(c, "domain_roles", []).map((r) => `**${pystr(r)}**`).join(", ") + (truthy(get(c, "domain_roles_rationale")) ? ` — ${pystr(c.domain_roles_rationale)}` : ""));
  P("");
  P("## Inbound communication");
  P("");
  P("| Collaborator | Type | Relationship | Message | Kind | Via | Payload |");
  P("|---|---|---|---|---|---|---|");
  let n = 0;
  for (const coll of get(c, "inbound", [])) {
    for (const m of get(coll, "messages", [])) {
      n++;
      P(`| ${cell(pname(f, parties, coll.collaborator))} (\`${pystr(coll.collaborator)}\`) | ${pkind(f, parties, coll.collaborator)} | ${cell(get(coll, "relationship"))} | \`${pystr(m.id)}\` ${cell(get(m, "name", mname(facts, m.id)))} | ${pystr(get(m, "kind"))} | ${cell(via(m))} | ${cell(payload(m))} |`);
    }
  }
  if (n === 0) P("| — | | | _nothing comes in (internally triggered?)_ | | | |");
  const rms = [...f.read_models, ...or(get(c, "read_models"), []).filter((r) => isDict(r) && truthy(get(r, "name")))]; // discover's + this canvas's own
  if (rms.length) {
    P("");
    P("_Read models that inform its commands_: " + rms.map(readModel).join("; "));
  }
  P("");
  P("## Ubiquitous language");
  P("");
  P("| Term | Meaning in this context | Avoid |");
  P("|---|---|---|");
  for (const t of get(c, "ubiquitous_language", [])) {
    P(`| **${cell(get(t, "term"))}** | ${cell(get(t, "definition"))} | ${cell(or(get(t, "avoid", []).join(", "), "—"))} |`);
  }
  if (!truthy(get(c, "ubiquitous_language"))) P("| — | _no context-specific terms recorded_ | |");
  P("");
  P("## Business decisions");
  P("");
  get(c, "business_decisions", []).forEach((d, i) => P(`${i + 1}. ${pystr(d)}`));
  P("");
  P("## Outbound communication");
  P("");
  P("| Message | Kind | Via | Payload | Collaborator | Type | Relationship |");
  P("|---|---|---|---|---|---|---|");
  n = 0;
  const outIds = new Set();
  for (const coll of get(c, "outbound", [])) {
    for (const m of get(coll, "messages", [])) {
      n++;
      outIds.add(get(m, "id"));
      P(`| \`${pystr(m.id)}\` ${cell(get(m, "name", mname(facts, m.id)))} | ${pystr(get(m, "kind"))} | ${cell(via(m))} | ${cell(payload(m))} | ${cell(pname(f, parties, coll.collaborator))} (\`${pystr(coll.collaborator)}\`) | ${pkind(f, parties, coll.collaborator)} | ${cell(get(coll, "relationship"))} |`);
    }
  }
  if (n === 0) P("| — | | | | _nothing goes out to a known collaborator_ | | |");
  const unconsumed = f.owns_events.filter((e) => !outIds.has(e.id)).map((e) => e.id); // from the canvas rows, not from connect.json
  if (unconsumed.length) {
    P("");
    P("_Also emits (no consumer known yet)_: " + unconsumed.map((e) => `\`${e}\``).join(", "));
  }
  P("");
  P("## Assumptions");
  P("");
  for (const a of or(get(c, "assumptions", []), ["_None recorded._"])) P(`- ${pystr(a)}`);
  P("");
  P("## Verification metrics");
  P("");
  for (const m of or(get(c, "verification_metrics", []), ["_None recorded._"])) P(`- ${pystr(m)}`);
  P("");
  P("## Open questions");
  P("");
  for (const q of or(get(c, "open_questions", []), ["_None open._"])) P(`- ${pystr(q)}`);
  const qas = get(define, "quality_attributes", []).filter((q) => get(q, "context") === X);
  P("");
  P("## Quality attributes");
  P("");
  if (qas.length) {
    P("| Attribute | Priority | Requirement | Scenario |");
    P("|---|---|---|---|");
    const rank = (q) => PRIORITY_RANK[get(q, "priority")] ?? 3;
    for (const q of [...qas].sort((a, b) => rank(a) - rank(b))) {
      P(`| ${cell(get(q, "attribute"))} | ${pystr(get(q, "priority"))} | ${cell(get(q, "requirement"))} | ${cell(get(q, "scenario"))} |`);
    }
  } else {
    P("_None yet — not a core context at this depth; see `system-context.md`._");
  }
  if (truthy(get(c, "model_traits"))) {
    P("");
    P("## Model traits and design notes");
    P("");
    const traits = Array.isArray(c.model_traits) ? c.model_traits : [c.model_traits];
    for (const t of traits) P(`- ${pystr(t)}`);
  }
  P("");
  P("---");
  P(`_Layout: Bounded Context Canvas v5 (ddd-crew). Sources: \`${ws.rel}/03-decompose\`, \`04-strategize\`, \`05-connect\`, \`06-organise\`, \`02-discover\`. Downstream: \`ddd-code\` reads this canvas and \`define.json\`._`);
  return L.join("\n") + "\n";
}

// ---------- "In plain words" (envelope `plain_words`, artifact-contract.md §3) ----------
function plainWordsBlock(doc) {
  const pw = get(or(doc, {}), "plain_words");
  if (!isDict(pw)) return [];
  const [what, decided, assumed, riskiest] = ["what", "decided", "assumed", "riskiest"].map((k) => pystrip(pystr(or(get(pw, k), ""))));
  if (!(what || decided || assumed || riskiest)) return [];
  const block = ["## In plain words", ""];
  if (what) block.push(what, "");
  for (const [lbl, value] of [["Decided", decided], ["Assumed", assumed], ["Riskiest", riskiest]]) {
    if (value) block.push(`**${lbl}:** ${value}`, "");
  }
  return [...block, "---", ""];
}

// ---------------------------------------------------------------- render system context
function renderSystem(ws, define, facts, system, parties) {
  const L = [];
  const P = (s) => L.push(s);
  P(`# System context — ${pystr(system.title)}`);
  P("");
  L.push(...plainWordsBlock(define));
  P(`<!-- ${MARK} from ${ws.rel}/07-define/define.json on ${now()}. Edit define.json and re-render; delete this line to protect hand edits. -->`);
  P("");
  const one = pystrip(or(get(system, "one_liner"), ""));
  P((one ? pyrstrip(one, ".") + ". " : "") +
    "C4 level 1: the system as a single box, the people who use it and the external systems it depends on. " +
    "No technology or internal structure here — that lives in the bounded context canvases and in `ddd-code`.");
  P("");
  P("```mermaid");
  P(pyrstrip(pystr(get(define, "system_context_c4_mermaid", ""))));
  P("```");
  P("");
  P("## People and external systems");
  P("");
  P("| Party | Type | Sends to the system | Receives from the system |");
  P("|---|---|---|---|");
  const partiesTbl = new Map();
  for (const c of get(define, "canvases", [])) {
    const f = facts.get(c.context);
    if (!truthy(f)) continue;
    for (const [side, key, arrow] of [["inbound", "in", "→"], ["outbound", "out", "←"]]) {
      for (const coll of get(c, side, [])) {
        const k = pkind(f, parties, coll.collaborator);
        if (k === "person" || k === "external system") {
          if (!partiesTbl.has(coll.collaborator)) partiesTbl.set(coll.collaborator, { name: pname(f, parties, coll.collaborator), type: k, in: [], out: [] });
          const p = partiesTbl.get(coll.collaborator);
          for (const m of get(coll, "messages", [])) {
            const s = `${pystr(get(m, "name", m.id))} ${arrow} \`${c.context}\``;
            if (!p[key].includes(s)) p[key].push(s);
          }
        }
      }
    }
  }
  for (const [pid, p] of partiesTbl) P(`| ${cell(p.name)} (\`${pystr(pid)}\`) | ${p.type} | ${cell(or(p.in.join("; "), "—"))} | ${cell(or(p.out.join("; "), "—"))} |`);
  if (!partiesTbl.size) P("| — | | | |");
  P("");
  P("## Bounded contexts and deployables");
  P("");
  P(`_Topology_: ${or(get(system, "topology_style"), "—")}, ${system.deployables.length} deployable(s), ${system.teams.length} team(s).`);
  P("");
  P("| Context | Purpose | Domain | Roles | Team | Deployable | Canvas |");
  P("|---|---|---|---|---|---|---|");
  for (const c of get(define, "canvases", [])) {
    const f = facts.get(c.context);
    if (!truthy(f)) continue;
    const team = or(f.team, {}), dep = or(f.deployable, {});
    const link = pystr(c.canvas_path).split("/07-define/").pop();
    P(`| **${cell(or(get(c, "name"), f.name))}** (\`${c.context}\`) | ${cell(firstSentence(get(c, "purpose")))} | ${pystr(get(get(c, "strategic_classification", {}), "domain", "—"))} | ${cell(get(c, "domain_roles", []).join(", "))} | ${cell(get(team, "name"))} | ${cell(get(dep, "name"))} (${pystr(get(dep, "kind", "—"))}) | [${link}](${link}) |`);
  }
  P("");
  P("### Context relationships (from decompose)");
  P("");
  P("| Id | Upstream | Downstream | Pattern | Why |");
  P("|---|---|---|---|---|");
  for (const r of system.relationships) {
    P(`| ${pystr(get(r, "id"))} | \`${pystr(get(r, "upstream"))}\` | \`${pystr(get(r, "downstream"))}\` | ${pystr(get(r, "pattern"))} | ${cell(get(r, "description"))} |`);
  }
  if (!system.relationships.length) P("| — | | | | |");
  P("");
  P("## Quality attributes (Quality Storming, light)");
  P("");
  const qas = get(define, "quality_attributes", []);
  if (truthy(qas)) {
    P("| Context | Attribute | Priority | Requirement | Scenario |");
    P("|---|---|---|---|---|");
    const ordered = [...facts.keys()].sort((a, b) => {
      const ka = facts.get(a).classification.domain !== "core" ? 1 : 0;
      const kb = facts.get(b).classification.domain !== "core" ? 1 : 0;
      return ka - kb || (a < b ? -1 : a > b ? 1 : 0);
    });
    const order = new Map(ordered.map((X, i) => [X, i]));
    const key = (q) => [order.get(get(q, "context")) ?? 99, PRIORITY_RANK[get(q, "priority")] ?? 3];
    for (const q of [...qas].sort((a, b) => { const [x1, y1] = key(a), [x2, y2] = key(b); return x1 - x2 || y1 - y2; })) {
      P(`| \`${pystr(get(q, "context"))}\` | ${cell(get(q, "attribute"))} | ${pystr(get(q, "priority"))} | ${cell(get(q, "requirement"))} | ${cell(get(q, "scenario"))} |`);
    }
  } else {
    P("_None recorded._");
  }
  P("");
  P("_Constraints these trace to (understand)_: " + or(system.constraints.map((c) => `${pystr(get(c, "id"))} [${pystr(get(c, "kind"))}] ${pystr(get(c, "text"))}`).join("; "), "—"));
  P("");
  P("## Open questions and assumptions (this step)");
  P("");
  for (const a of get(define, "assumptions", [])) P(`- Assumption ${pystr(get(a, "id"))} (${pystr(get(a, "confidence"))}): ${pystr(get(a, "text"))}`);
  for (const q of get(define, "open_questions", [])) P(`- Question ${pystr(get(q, "id"))}${truthy(get(q, "blocking")) ? " — BLOCKING" : ""} (owner: ${pystr(get(q, "owner", "—"))}): ${pystr(get(q, "text"))}`);
  for (const nt of get(define, "notes_for_downstream", [])) P(`- Note ${pystr(get(nt, "id"))} for ${get(nt, "for", []).join(", ")} (${pystr(get(nt, "kind", "other"))}): ${pystr(get(nt, "text"))}`);
  if (!truthy(get(define, "assumptions")) && !truthy(get(define, "open_questions")) && !truthy(get(define, "notes_for_downstream"))) P("_None._");
  P("");
  P("---");
  P("_Notation: C4 model level 1 (c4model.com); rendered with Mermaid `C4Context`. Persons are people, `System_Ext` are systems outside our control._");
  return L.join("\n") + "\n";
}

// ---------------------------------------------------------------- glossary
function norm(s) {
  return pystrip(or(s, "")).toLowerCase().replace(/\s+/g, " ").replace(/[\s.]+$/, "");
}

function renderGlossary(ws, define, facts, system) {
  const text = or(ws.glossary_md, `# Ubiquitous language: ${pystr(system.title)}\n\n## Shared\n`);
  const head = [], sections = new Map();
  let cur = null;
  for (const line of splitlines(text)) {
    if (hasMark(line)) continue; // an earlier render's marker is never carried over: exactly one is written below
    if (line.startsWith("## ")) {
      cur = pystrip(line.slice(3));
      sections.set(cur, []);
      continue;
    }
    (truthy(cur) ? sections.get(cur) : head).push(line);
  }
  const sharedDefs = new Map();
  for (const e of parseGlossary(text).get("Shared") || []) sharedDefs.set(e.term, e.definition);
  const ctxHeadings = new Set();
  for (const c of get(define, "canvases", [])) {
    const f = facts.get(c.context);
    const nm = or(get(c, "name"), truthy(f) ? f.name : c.context);
    ctxHeadings.add(`${pystr(nm)} context`.toLowerCase());
    ctxHeadings.add(`${c.context} context`.toLowerCase());
  }
  const kept = new Map([...sections].filter(([h]) => !ctxHeadings.has(h.toLowerCase()) && !h.toLowerCase().endsWith(" context (deprecated)")));
  // a Shared term that two or more contexts define differently is a boundary: flag it on the Shared line, keep the definition
  const ctxDefs = new Map();
  for (const c of get(define, "canvases", [])) {
    for (const t of get(c, "ubiquitous_language", [])) {
      if (!ctxDefs.has(get(t, "term"))) ctxDefs.set(get(t, "term"), new Set());
      ctxDefs.get(get(t, "term")).add(norm(get(t, "definition")));
    }
  }
  // Written with a plain hyphen (some repos ban em dashes), but recognised in any dash form so a
  // re-run over a glossary an earlier version wrote does not append a second marker to the line.
  const SPLIT = "_(meaning differs by context - see below)_";
  const SPLIT_RE = /_\(meaning differs by context\s*[-\u2013\u2014]\s*see below\)_/;
  const out = [...head];
  while (out.length && !pystrip(out[out.length - 1])) out.pop();
  out.push("");
  for (const [h, body0] of kept) {
    out.push(`## ${h}`);
    const body = [...body0];
    while (body.length && !pystrip(body[body.length - 1])) body.pop();
    if (h === "Shared") {
      for (let i = 0; i < body.length; i++) {
        const line = body[i];
        const m = line.match(/^\*\*(.+?)\*\*/);
        if (m && !SPLIT_RE.test(line)) {
          const term = pystrip(m[1]);
          const all = ctxDefs.get(term) ?? new Set();
          const defs = new Set([...all].filter((d) => d !== norm(sharedDefs.get(term) ?? null)));
          if (defs.size >= 1 && all.size >= 2) body[i] = pyrstrip(line) + " " + SPLIT;
        }
      }
    }
    out.push(...body);
    out.push("");
  }
  out.push(`<!-- per-context sections below are ${MARK} from ${ws.rel}/07-define/define.json; edit define.json (canvases[].ubiquitous_language) and re-render -->`);
  out.push("");
  for (const c of get(define, "canvases", [])) {
    const f = facts.get(c.context);
    const nm = or(get(c, "name"), truthy(f) ? f.name : c.context);
    out.push(`## ${pystr(nm)} context`);
    const specific = [], sameAsShared = [];
    for (const t of get(c, "ubiquitous_language", [])) {
      const sd = sharedDefs.has(get(t, "term")) ? sharedDefs.get(get(t, "term")) : null;
      (sd !== null && norm(sd) === norm(get(t, "definition")) ? sameAsShared : specific).push(t);
    }
    for (const t of specific) {
      let line = `**${pystr(get(t, "term"))}** — ${pyrstrip(pystr(get(t, "definition", "")), ".")}.`;
      if (truthy(get(t, "avoid"))) line += ` _Avoid_: ${t.avoid.join(", ")}`;
      if (sharedDefs.has(get(t, "term"))) line += " _(differs from the shared meaning — a boundary)_";
      out.push(line);
    }
    if (sameAsShared.length) out.push(`_Uses the shared meaning of_: ${sameAsShared.map((t) => "**" + pystr(t.term) + "**").join(", ")}`);
    if (!specific.length && !sameAsShared.length) out.push("_No context-specific terms recorded yet._");
    out.push("");
  }
  return pyrstrip(out.join("\n"), "\n") + "\n";
}

// ---------------------------------------------------------------- main
// The generated-line guard (invariant 4): a file that exists, is not blank and no longer
// carries MARK was edited by hand, so it is skipped unless --force.
function write(file, content, force, skipped) {
  if (fs.existsSync(file) && !force) {
    const old = fs.readFileSync(file, "utf8").replace(/\r\n?/g, "\n");
    if (!hasMark(old) && pystrip(old)) { skipped.push(file); return false; }
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  return true;
}

const SPEC = {
  "--context": { dest: "context", nargs: "*" },
  "--check-only": { dest: "check_only", action: "store_true" },
  "--force": { dest: "force", action: "store_true" },
  "--no-glossary": { dest: "no_glossary", action: "store_true" },
};
const USAGE = "usage: ddd define render [ddd_dir] [--context [ID ...]] [--check-only] [--force] [--no-glossary]";

export function main(argv) {
  const out = (s) => process.stdout.write(s);
  let a;
  try {
    a = parseArgs(SPEC, argv);
  } catch (e) {
    if (e instanceof UsageError) { process.stderr.write(`${USAGE}\nddd define render: error: ${e.message}\n`); return 2; }
    throw e;
  }
  if (a.help) { out(USAGE + "\n"); return 0; }
  try {
    return run(a, out);
  } catch (e) {
    if (e instanceof ExitError) { process.stderr.write(e.message + "\n"); return e.exitCode; }
    throw e;
  }
}

function run(a, out) {
  const ws = loadWorkspace(a.ddd_dir);
  const define = ws.steps.define;
  if (!truthy(define)) throw new ExitError(`error: ${path.join(ws.ddd_dir, "07-define/define.json")} not found — run ddd define prefill --write first`);
  const [facts, system] = buildFacts(ws);
  const parties = partyIndex(ws);
  const only = truthy(a.context) ? new Set(a.context) : null;
  const [errors, warnings] = lint(ws, define, facts, parties, only);
  for (const w of warnings) out(`warning: ${w}\n`);
  if (errors.length) {
    out(`\n${errors.length} lint error(s) — nothing rendered:\n`);
    for (const e of errors) out(`  - ${e}\n`);
    return 1;
  }
  out("lint: OK\n");
  if (a.check_only) return 0;
  const written = [], skipped = [];
  for (const c of define.canvases) {
    if (only && !only.has(c.context)) continue;
    const file = pyjoin(ws.project_root, c.canvas_path);
    if (write(file, renderCanvas(ws, define, facts, parties, c), a.force, skipped)) written.push(file);
  }
  const sysPath = path.join(ws.ddd_dir, "07-define", "system-context.md");
  if (write(sysPath, renderSystem(ws, define, facts, system, parties), a.force, skipped)) written.push(sysPath);
  if (!a.no_glossary) {
    const gpath = path.join(ws.ddd_dir, "glossary.md");
    const content = renderGlossary(ws, define, facts, system);
    fs.mkdirSync(ws.ddd_dir, { recursive: true });
    fs.writeFileSync(gpath, content);
    written.push(gpath);
  }
  for (const p of written) out(`wrote ${p}\n`);
  for (const p of skipped) out(`skipped (hand-edited, no marker; use --force to overwrite): ${p}\n`);
  const pre = path.join(ws.ddd_dir, "07-define", ".prefill");
  if (!only && fs.existsSync(pre) && fs.statSync(pre).isDirectory()) {
    fs.rmSync(pre, { recursive: true, force: true });
    out(`removed ${pre} (pre-fill briefs are scaffolding; re-run ddd define prefill to regenerate them)\n`);
  }
  return 0;
}
