// Shared port of contracts.py's helpers for `ddd contracts prefill|check|render`.
//
// Everything here mirrors the Python twin line for line, because the goldens pin its
// stdout, stderr, exit code and every written file byte for byte, and the wording is
// kept Python-era (`run contracts.py prefill first`) until leaf 1.4.1 rewords code and
// goldens together. Where Python semantics differ from JavaScript's (truthiness, repr(),
// dict key order, set membership with None) the helper says so.
//
// The JSON-Schema validator lives in ../../../shared/lib/jsonschema.mjs, which is the
// port of the same Python code; it is imported, not re-ported.
//
// Zero dependencies, ESM, Node >= 18.
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { FOLDER, projectRoot, resolvePath } from "../../../shared/lib/workspace.mjs";
import { pyDumps, pyRepr, pyStr } from "../../../shared/lib/jsonschema.mjs";

export { FOLDER, projectRoot, resolvePath, pyDumps, pyRepr, pyStr };

export const ENTITY_STATUS = ["Draft", "In Review", "Approved", "Archived", "Deprecated", "Rejected", "Unprocessed"];
export const PATTERNS = ["partnership", "shared-kernel", "customer-supplier", "conformist", "anticorruption-layer",
  "open-host-service", "published-language", "separate-ways"]; // = shared/schemas/contracts.schema.json
// connect `messages[].contract` / define canvas `relationship` values that are not context-map patterns.
// `external-api` is resolved per message against the wrapping context (see wrapperPattern).
export const PATTERN_ALIASES = { ui: "open-host-service", "user-interaction": "open-host-service" };
export const SYNC_VIAS = ["http", "grpc", "in-process"];
export const DELIVERIES = ["at-most-once", "at-least-once", "exactly-once", "sync"];
export const VIAS = ["http", "grpc", "message-bus", "in-process", "file", "db", "other"];
export const KINDS = ["event", "command", "query"]; // never `response`: a response belongs to its request
export const REQUIRED_KEYS = ["id", "kind", "name", "description", "entityStatus", "version", "domain", "owners",
  "consumers", "reviewers", "pattern", "delivery", "via", "schema", "example",
  "semantics", "termsOfUse", "provenance"];
export const LIST_KEYS = ["owners", "consumers", "reviewers", "semantics"];
export const COMPANIONS = ["request", "response"];
// No `s` flag: Python's MARK_RE has no DOTALL, so the marker must sit on one line.
export const MARK_RE = /generated by ddd[- ]contracts\b.*?entries-sha256:\s*([0-9a-f]{16})/;
const KEBAB_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const IDENT_RE = /^\s*([A-Za-z_][A-Za-z0-9_]*)/;

// ---------------------------------------------------------------------------
// Python value semantics.
// ---------------------------------------------------------------------------
export const isDict = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
export const has = (o, k) => isDict(o) && Object.prototype.hasOwnProperty.call(o, k);
// `d.get(k)`: None when absent; the value (which may itself be None) otherwise.
export const get = (o, k, dflt = null) => (has(o, k) ? o[k] : dflt);
// Python truthiness: None, False, 0, "", [], {} are false.
export function truthy(v) {
  if (v === null || v === undefined || v === false || v === 0) return false;
  if (typeof v === "string" || Array.isArray(v)) return v.length > 0;
  if (isDict(v)) return Object.keys(v).length > 0;
  return true;
}
// `x or y`.
export const or = (a, b) => (truthy(a) ? a : b);
// `str.strip()` / `rstrip()`: Python strips Unicode whitespace, as JS trim does.
export const strip = (s) => String(s).trim();
export const isKebab = (s) => KEBAB_RE.test(s);
// `[x for x in list if isinstance(x, dict)]` guard for values that may not be a list.
export const asList = (v) => (Array.isArray(v) ? v : []);
export const asDict = (v) => (isDict(v) ? v : {});
// `x in some_list` with Python `==` (strings and None only ever get here).
export const pyIn = (v, list) => asList(list).some((x) => x === v || (x === null && v === undefined));
// sorted() of strings: Python orders by code point; JS `<` orders by UTF-16 unit, the
// same thing for everything in the BMP.
export const cmpStr = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
export const sorted = (xs) => [...xs].sort(cmpStr);
// list(dict.fromkeys(xs)): dedupe, first occurrence wins.
export const uniq = (xs) => [...new Set(xs)];
// str.format `{x:<N}`: left-justify by code points.
export const ljust = (s, n) => {
  const len = [...s].length;
  return len >= n ? s : s + " ".repeat(n - len);
};

export class Report {
  constructor() { this.errors = []; this.warnings = []; this.notes = []; }
  err(m) { this.errors.push(m); }
  warn(m) { this.warnings.push(m); }
  note(m) { this.notes.push(m); }
}

// Raised for a Python `sys.exit(2)` / `return 2` with a message on stderr.
export class IoError extends Error {
  constructor(message, code = 2) { super(message); this.exitCode = code; }
}

// ---------------------------------------------------------------------------
// Files.
// ---------------------------------------------------------------------------
// json.load(): raises on bad JSON. Python's JSONDecodeError text cannot be reproduced
// from JSON.parse, so the message that follows `invalid JSON in <path>:` is V8's.
export function loadJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}
export function loadJsonOrNull(p) {
  try { return loadJson(p); } catch { return null; }
}
// json.dump(indent=2, ensure_ascii=False) + "\n".
export function saveJson(p, data) {
  fs.writeFileSync(p, pyDumps(data, { indent: 2, ensureAscii: false }) + "\n");
}
// open(errors="ignore").read(), or None when the file cannot be read.
export function readText(p) {
  try { return fs.readFileSync(p, "utf8"); } catch { return null; }
}
export const exists = (p) => fs.existsSync(p);

export function ids(items, key = "id") {
  return asList(items).filter((x) => isDict(x) && get(x, key) !== null).map((x) => x[key]);
}

export function slug(s) {
  return strip(s).toLowerCase().replace(/[^a-z0-9 -]/g, "").replace(/ /g, "-");
}

// " ".join(w.capitalize() for w in s.split("-")): capitalize() lowercases the rest.
export function titlecase(mid) {
  return pyStr(mid).split("-").map((w) => (w ? w[0].toUpperCase() + w.slice(1).toLowerCase() : "")).join(" ");
}

// Covers everything contracts.md renders. plain_words is rendered too, so an edit to it
// must make the file stale; otherwise the summary a human reads can drift from the JSON.
export function entriesHash(entries, plainWords = null) {
  const payload = truthy(plainWords) ? [entries, plainWords] : entries;
  return createHash("sha256").update(pyDumps(payload, { sortKeys: true, ensureAscii: false }), "utf8").digest("hex").slice(0, 16);
}

// Property name of a connect payload entry: the leading identifier, so
// `completionEvidence{photoUris, meterReadings}` and `recipeIds[]` both name the property.
export function payloadName(p) {
  const s = pyStr(or(p, ""));
  const m = IDENT_RE.exec(s);
  if (m) return m[1];
  return strip(s) || null;
}

// Every property name in a schema, at any depth.
export function propertyNames(schema, out = new Set()) {
  if (isDict(schema)) {
    for (const [k, sub] of Object.entries(asDict(get(schema, "properties")))) {
      out.add(k);
      propertyNames(sub, out);
    }
    for (const key of ["items", "additionalProperties"]) {
      if (isDict(get(schema, key))) propertyNames(schema[key], out);
    }
  }
  return out;
}

// load_workspace: only the five upstream artifacts contracts.py reads; a corrupt one is
// an IO error (exit 2), a corrupt manifest is just an empty manifest.
export function loadWorkspace(dddDir) {
  const A = {};
  for (const s of ["discover", "decompose", "organise", "connect", "define"]) {
    const p = path.join(dddDir, FOLDER[s], `${s}.json`);
    if (exists(p)) {
      try {
        A[s] = loadJson(p);
      } catch (e) {
        throw new IoError(`error: invalid JSON in ${p}: ${e.message}`);
      }
    }
  }
  const mpath = path.join(dddDir, "manifest.json");
  if (exists(mpath)) A.manifest = or(loadJsonOrNull(mpath), {});
  A.glossary_text = readText(path.join(dddDir, "glossary.md"));
  return A;
}

export function relPrefix(A, dddDir) {
  const m = asDict(get(A, "manifest"));
  const base = path.basename(dddDir.replace(/\/+$/, ""));
  return String(or(get(m, "ddd_dir"), or(base, "ddd"))).replace(/^\/+|\/+$/g, "");
}

// (bounded-context ids in decompose order, id -> name, external-system ids, human-actor ids).
// `names` is a Map so a context without an id keys on null the way a Python dict does.
export function partySets(A) {
  const dc = asDict(get(A, "decompose"));
  const bcs = asList(get(dc, "bounded_contexts"));
  const contexts = ids(bcs);
  const names = new Map();
  for (const b of bcs) if (isDict(b)) names.set(get(b, "id"), or(get(b, "name"), get(b, "id")));
  const dv = asDict(get(A, "discover"));
  const externals = new Set(ids(get(dv, "external_systems")));
  const actors = new Set(ids(get(dv, "actors")));
  for (const p of asList(get(asDict(get(A, "connect")), "parties"))) {
    if (!isDict(p)) continue;
    (get(p, "kind") === "external-system" ? externals : actors).add(get(p, "id"));
  }
  return { contexts, names, externals, actors };
}

function blankMessage(mid, kind, producer, source) {
  return { id: mid, kind, producer, consumers: [], pattern: null, payload: [], response_payload: [],
    delivery: null, idempotency: "", description: "", name: "", channels: [], flows: [], vias: [], syncs: [], source };
}

// context id -> the set of deployable ids that host it (organise.deployables[].contexts).
export function placement(A) {
  const out = new Map();
  for (const d of asList(get(asDict(get(A, "organise")), "deployables"))) {
    if (!isDict(d)) continue;
    for (const c of asList(get(d, "contexts"))) {
      if (!truthy(c)) continue;
      if (!out.has(c)) out.set(c, new Set());
      out.get(c).add(get(d, "id"));
    }
  }
  return out;
}

// (cross-party messages, in-process messages), both as Maps in insertion order.
//
// Cross-party = each connect.messages[] entry whose consumer set differs from {producer}, plus
// each flow step between two different parties whose message has no messages[] entry, minus
// anything organise puts inside a single deployable. A human on one end is in scope (that is
// the UI/API contract); a human on both ends and `kind: response` are not. Everything
// uncertain stays cross-party: a contract too many is a review comment, too few is an outage.
export function crossParty(A) {
  const cn = asDict(get(A, "connect"));
  const { externals, actors } = partySets(A);
  const software = (p) => truthy(p) && !actors.has(p);
  const out = new Map();
  for (const m of asList(get(cn, "messages"))) {
    if (!isDict(m)) continue;
    const mid = get(m, "id");
    const cons = asList(get(m, "consumers")).filter(truthy);
    const producer = get(m, "producer");
    if (!truthy(mid) || !cons.length || setEq(new Set(cons), new Set([producer])) || get(m, "kind") === "response") continue;
    if (!software(producer) && !cons.some(software)) continue;
    const e = blankMessage(mid, get(m, "kind"), producer, "messages");
    Object.assign(e, {
      consumers: uniq(cons),
      pattern: get(m, "contract"),
      payload: [...asList(get(m, "payload"))],
      response_payload: [...asList(get(m, "response_payload"))],
      delivery: get(m, "delivery"),
      idempotency: strip(pyStr(or(get(m, "idempotency"), ""))),
      description: strip(pyStr(or(get(m, "description"), ""))),
      name: strip(pyStr(or(get(m, "name"), ""))),
      channels: asList(get(m, "channels")).filter(isDict),
    });
    out.set(mid, e);
  }
  for (const f of asList(get(cn, "flows"))) {
    if (!isDict(f)) continue;
    for (const s of asList(get(f, "steps"))) {
      if (!isDict(s)) continue;
      const mid = get(s, "message");
      const frm = get(s, "from");
      const to = get(s, "to");
      if (!truthy(mid) || get(s, "kind") === "response") continue;
      let e = out.get(mid);
      if (e === undefined) {
        if (!truthy(frm) || !truthy(to) || frm === to || !(software(frm) || software(to))) continue;
        e = blankMessage(mid, get(s, "kind"), frm, "flow");
        out.set(mid, e);
      }
      if (e.source === "flow" && truthy(to) && to !== e.producer && !e.consumers.includes(to)) e.consumers.push(to);
      const fid = get(f, "id");
      if (truthy(fid) && !e.flows.includes(fid)) e.flows.push(fid);
      if (truthy(get(s, "via"))) e.vias.push(s.via);
      e.syncs.push(truthy(get(s, "sync")));
    }
  }
  for (const e of out.values()) {
    if (e.source === "flow" && !truthy(e.delivery) && e.syncs.length && e.syncs.every(Boolean)) e.delivery = "sync";
  }
  const placed = placement(A);
  // The deployable hosting producer and every consumer, or null if that is not certain.
  const oneDeployable = (e) => {
    if (!placed.size) return null;
    const parties = [e.producer, ...e.consumers];
    if (parties.some((p) => !truthy(p) || actors.has(p) || externals.has(p))) return null;
    const units = parties.map((p) => placed.get(p) || new Set());
    if (units.some((u) => u.size !== 1)) return null;
    return units.every((u) => setEq(u, units[0])) ? [...units[0]][0] : null;
  };
  const inproc = new Map();
  for (const mid of [...out.keys()]) {
    const unit = oneDeployable(out.get(mid));
    if (truthy(unit)) {
      out.get(mid).deployable = unit;
      inproc.set(mid, out.get(mid));
      out.delete(mid);
    }
  }
  return { xp: out, inproc };
}

function setEq(a, b) {
  if (a.size !== b.size) return false;
  for (const x of a) if (!b.has(x)) return false;
  return true;
}

// sorted(inproc.items()): by message id.
export const sortedEntries = (m) => [...m.entries()].sort((a, b) => cmpStr(a[0], b[0]));

// (primary transport, the other channels as objects). The flow steps' `via` wins; a
// catalogue-only message falls back to its `channels[]`. A sync message never keeps `file`
// as primary when a synchronous transport is listed. The extra channels keep connect's whole
// {via, sync, delivery, note} object: a second transport is a second promise.
//
// Python picks `max(set(cands), key=cands.count)`, whose tie-break follows set iteration
// order; here a tie goes to the transport seen first, which is the only deterministic reading.
export function chooseVia(info) {
  const vias = asList(get(info, "vias")).filter(truthy);
  const objs = asList(get(info, "channels")).filter((c) => isDict(c) && truthy(get(c, "via")));
  const chan = objs.map((c) => c.via);
  const cands = vias.length ? vias : chan;
  if (!cands.length) return ["TODO", []];
  let primary = null;
  let best = -1;
  for (const v of uniq(cands)) {
    const n = cands.filter((x) => x === v).length;
    if (n > best) { best = n; primary = v; }
  }
  if (get(info, "delivery") === "sync" && !SYNC_VIAS.includes(primary)) {
    primary = [...cands, ...chan].find((v) => SYNC_VIAS.includes(v)) ?? primary;
  }
  const detail = new Map();
  for (const c of objs) detail.set(c.via, { ...c });
  // a transport seen only on a flow step has no object upstream, so it gets a bare one
  const others = uniq([...vias, ...chan]).filter((v) => v !== primary).map((v) => detail.get(v) || { via: v });
  return [primary, others];
}

// Just the transports, for a summary line or a table cell.
export function channelNames(chans) {
  return asList(chans).filter((c) => isDict(c) && truthy(get(c, "via"))).map((c) => pyStr(c.via)).join(", ");
}

// `file (at-most-once, async): the warehouse picks the week up from the nightly pick-list`.
export function channelLines(chans) {
  const out = [];
  for (const c of asList(chans)) {
    if (!isDict(c) || !truthy(get(c, "via"))) continue;
    const bits = truthy(get(c, "delivery")) ? [pyStr(c.delivery)] : [];
    if (get(c, "sync") !== null) bits.push(truthy(c.sync) ? "sync" : "async");
    let line = pyStr(c.via) + (bits.length ? ` (${bits.join(", ")})` : "");
    if (truthy(get(c, "note"))) line += `: ${pyStr(c.note)}`;
    out.push(line);
  }
  return out.join("; ");
}

export function discoverLookup(A, mid) {
  const dv = asDict(get(A, "discover"));
  for (const coll of ["events", "commands"]) {
    for (const x of asList(get(dv, coll))) if (isDict(x) && get(x, "id") === mid) return x;
  }
  return null;
}

export function findRelationship(A, producer, consumers) {
  const dc = asDict(get(A, "decompose"));
  const rels = asList(get(dc, "relationships")).filter(isDict);
  const ctxs = new Set(ids(get(dc, "bounded_contexts")));
  for (const c of consumers) {
    if (ctxs.has(producer) && ctxs.has(c)) {
      for (const r of rels) if (get(r, "upstream") === producer && get(r, "downstream") === c) return get(r, "id");
      for (const r of rels) if (setEq(new Set([get(r, "upstream"), get(r, "downstream")]), new Set([producer, c]))) return get(r, "id");
    }
  }
  return null;
}

// The relationship define recorded for this collaborator on the context's canvas.
export function canvasRelationship(A, ctx, collaborator) {
  for (const c of asList(get(asDict(get(A, "define")), "canvases"))) {
    if (!isDict(c) || get(c, "context") !== ctx) continue;
    for (const side of ["inbound", "outbound"]) {
      for (const coll of asList(get(c, side))) {
        if (isDict(coll) && get(coll, "collaborator") === collaborator) return get(coll, "relationship");
      }
    }
  }
  return null;
}

export function decomposePattern(A, aId, bId) {
  for (const r of asList(get(asDict(get(A, "decompose")), "relationships"))) {
    if (isDict(r) && setEq(new Set([get(r, "upstream"), get(r, "downstream")]), new Set([aId, bId]))) return get(r, "pattern");
  }
  return null;
}

export const alias = (p) => (typeof p === "string" && has(PATTERN_ALIASES, p) ? PATTERN_ALIASES[p] : p);

export function firstPattern(...candidates) {
  for (const c of candidates) if (PATTERNS.includes(alias(c))) return alias(c);
  return null;
}

// How our context wraps an external system: define's canvas relationship, else a decompose
// relationship, else `conformist`.
export function wrapperPattern(A, ctx, ext) {
  const p = firstPattern(canvasRelationship(A, ctx, ext), decomposePattern(A, ctx, ext));
  return p === "anticorruption-layer" || p === "conformist" ? p : or(p, "conformist");
}

export function teamsOwning(A, ctxIds) {
  const seen = [];
  for (const t of asList(get(asDict(get(A, "organise")), "teams"))) {
    if (!isDict(t)) continue;
    const owns = asList(get(t, "owns_contexts"));
    if (ctxIds.some((c) => owns.includes(c)) && !seen.includes(get(t, "id"))) seen.push(get(t, "id"));
  }
  return seen;
}

// Headings of glossary.md, as Python's `^#{1,6}\s+(.+?)\s*$` under re.M finds them.
export function glossaryHeadings(text) {
  const out = [];
  for (const m of String(text).matchAll(/^#{1,6}\s+(.+?)\s*$/gm)) out.push(m[1]);
  return out;
}

export function glossaryAnchor(A, rel, domain, names) {
  const text = get(A, "glossary_text");
  if (text === null) return null;
  const want = slug(`${pyStr(names.has(domain) ? names.get(domain) : domain)} context`);
  for (const h of glossaryHeadings(text)) if (slug(h) === want) return `${rel}/glossary.md#${want}`;
  return `${rel}/glossary.md`;
}

// "In plain words" block (envelope `plain_words`, artifact-contract.md section 3).
export function plainWordsBlock(doc) {
  const pw = get(asDict(doc), "plain_words");
  if (!isDict(pw)) return [];
  const [what, decided, assumed, riskiest] = ["what", "decided", "assumed", "riskiest"].map((k) => strip(pyStr(or(get(pw, k), ""))));
  if (!(what || decided || assumed || riskiest)) return [];
  const block = ["## In plain words", ""];
  if (what) block.push(what, "");
  for (const [label, value] of [["Decided", decided], ["Assumed", assumed], ["Riskiest", riskiest]]) {
    if (value) block.push(`**${label}:** ${value}`, "");
  }
  return [...block, "---", ""];
}

// ---------------------------------------------------------------------------
// Argument parsing: the argparse subset each subcommand used (an optional positional
// defaulting to `ddd`, `--flag value`, `--flag=value`, unique prefixes, choices,
// store_true, -h/--help). Usage errors are not golden-recorded, so the wording is plain.
// ---------------------------------------------------------------------------
export class UsageError extends Error {}

export function parseArgs(argv, options) {
  const res = { help: false, ddd_dir: "ddd" };
  for (const [name, o] of Object.entries(options)) res[o.dest] = o.flag ? false : (o.default ?? null);
  const names = Object.keys(options);
  const positional = [];
  let onlyPositional = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (onlyPositional || !a.startsWith("-") || a === "-") { positional.push(a); continue; }
    if (a === "--") { onlyPositional = true; continue; }
    if (a === "-h" || a === "--help") { res.help = true; return res; }
    const eq = a.indexOf("=");
    let name = eq >= 0 ? a.slice(0, eq) : a;
    const inline = eq >= 0 ? a.slice(eq + 1) : undefined;
    if (!options[name]) {
      const m = names.filter((n) => n.startsWith(name));
      if (m.length === 1) name = m[0];
      else if (m.length > 1) throw new UsageError(`ambiguous option: ${name} could match ${m.join(", ")}`);
      else throw new UsageError(`unrecognized arguments: ${a}`);
    }
    const o = options[name];
    if (o.flag) {
      if (inline !== undefined) throw new UsageError(`argument ${name}: ignored explicit argument '${inline}'`);
      res[o.dest] = true;
      continue;
    }
    let value = inline;
    if (value === undefined) {
      if (i + 1 >= argv.length || (argv[i + 1].startsWith("-") && argv[i + 1] !== "-")) throw new UsageError(`argument ${name}: expected one argument`);
      value = argv[++i];
    }
    if (o.choices && !o.choices.includes(value)) {
      throw new UsageError(`argument ${name}: invalid choice: '${value}' (choose from ${o.choices.map((c) => `'${c}'`).join(", ")})`);
    }
    res[o.dest] = value;
  }
  if (positional.length > 1) throw new UsageError(`unrecognized arguments: ${positional.slice(1).join(" ")}`);
  if (positional.length === 1) res.ddd_dir = positional[0];
  return res;
}

// The `main(argv, ctx)` wrapper every verb shares: parse, `<abs> does not exist` -> 2,
// IoError -> its message on stderr and its code, output through process.stdout.write so
// a piped stdout is never truncated by an early exit.
export async function runVerb({ argv, ctx, verb, options, usage, body }) {
  const prog = `ddd ${(ctx && ctx.words ? ctx.words : ["contracts", verb]).join(" ")}`;
  let a;
  try {
    a = parseArgs(argv, options);
  } catch (e) {
    if (e instanceof UsageError) {
      process.stderr.write(`usage: ${prog} ${usage}\n${prog}: error: ${e.message}\n`);
      return 2;
    }
    throw e;
  }
  if (a.help) {
    process.stdout.write(`usage: ${prog} ${usage}\n`);
    return 0;
  }
  const dddDir = path.resolve(a.ddd_dir);
  if (!(exists(dddDir) && fs.statSync(dddDir).isDirectory())) {
    process.stderr.write(`error: ${dddDir} does not exist\n`);
    return 2;
  }
  const outLines = [];
  const print = (s = "") => outLines.push(s);
  try {
    const code = body(a, dddDir, print);
    process.stdout.write(outLines.length ? outLines.join("\n") + "\n" : "");
    return code;
  } catch (e) {
    process.stdout.write(outLines.length ? outLines.join("\n") + "\n" : "");
    if (e instanceof IoError) {
      process.stderr.write(e.message + "\n");
      return e.exitCode;
    }
    throw e;
  }
}
