"""journeys.json -> Playwright TypeScript. A pure function of its inputs.

Determinism is the point: the same journeys.json and inventory.json must always
produce byte-identical files, so a diff in the generated tests always means a
real change upstream. That rules out timestamps, dict iteration order, and
anything read from the environment.

Generated tests never talk to Kafka or blob storage directly. They call helpers
in `support/`, which each adapter backs. That keeps the emitted spec readable --
a human reviewing a journey should see the journey, not transport plumbing.
"""
from __future__ import annotations

import json
from typing import Any

HEADER = (
    "// GENERATED by e2e-harness. Do not edit.\n"
    "// Source: e2e/journeys.json -> journey {jid!r}\n"
    "// Regenerate with: e2e build\n"
)


def _ts(value: Any) -> str:
    """JSON is a subset of TS object literal syntax, so this is safe and stable."""
    return json.dumps(value, sort_keys=True, ensure_ascii=False)


def _resource_map(inventory: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {r["id"]: r for r in inventory.get("resources", [])}


def _expectations(step: dict[str, Any], target: str, indent: str) -> list[str]:
    """Emit assertions shared by http / await_http."""
    out: list[str] = []
    if "expect_status" in step:
        exp = step["expect_status"]
        if isinstance(exp, list):
            out.append(f"{indent}expect({_ts(exp)}).toContain({target}.status);")
        else:
            out.append(f"{indent}expect({target}.status).toBe({exp});")
    if "expect_body_contains" in step:
        vals = step["expect_body_contains"]
        for v in (vals if isinstance(vals, list) else [vals]):
            out.append(f"{indent}expect({target}.text).toContain({_ts(v)});")
    if "expect_json_path" in step:
        for path, expected in sorted(step["expect_json_path"].items()):
            out.append(
                f"{indent}expect(jsonPath({target}.json, {_ts(path)}))"
                f".toEqual({_ts(expected)});"
            )
    return out


def _saves(step: dict[str, Any], target: str, indent: str) -> list[str]:
    out: list[str] = []
    for var, path in sorted((step.get("save_as") or {}).items()):
        out.append(f"{indent}ctx[{_ts(var)}] = jsonPath({target}.json, {_ts(path)});")
    return out


def emit_step(step: dict[str, Any], idx: int, res: dict[str, dict[str, Any]]) -> list[str]:
    kind = step["kind"]
    label = step.get("name") or f"{kind} #{idx + 1}"
    v = f"r{idx}"
    L = [f"    await test.step({_ts(label)}, async () => {{"]
    body = "      "

    if kind in ("http", "await_http"):
        rid = step["resource"]
        opts = {
            "method": step["method"],
            "path": step["path"],
            "headers": step.get("headers") or {},
            "query": step.get("query") or {},
        }
        if "body" in step:
            opts["body"] = step["body"]
        if kind == "http":
            L.append(f"{body}const {v} = await http({_ts(rid)}, {_ts(opts)}, ctx);")
            L += _expectations(step, v, body)
        else:
            checks = {k: step[k] for k in
                      ("expect_status", "expect_body_contains", "expect_json_path")
                      if k in step}
            L.append(
                f"{body}const {v} = await awaitHttp({_ts(rid)}, {_ts(opts)}, "
                f"{_ts(checks)}, {step['timeout_ms']}, "
                f"{step.get('interval_ms', 500)}, ctx);"
            )
        L += _saves(step, v, body)

    elif kind == "browser":
        rid = step["resource"]
        base = res.get(rid, {}).get("base_url") or "http://localhost"
        L.append(f"{body}await page.goto({_ts(base + (step.get('path') or '/'))});")
        for action in step.get("actions", []):
            if not isinstance(action, dict):
                continue
            a = action.get("action")
            sel = action.get("selector")
            if a == "click":
                L.append(f"{body}await page.click({_ts(sel)});")
            elif a == "fill":
                L.append(f"{body}await page.fill({_ts(sel)}, {_ts(action.get('value', ''))});")
            elif a == "press":
                L.append(f"{body}await page.press({_ts(sel)}, {_ts(action.get('key', 'Enter'))});")
            elif a == "wait_for":
                L.append(
                    f"{body}await page.waitForSelector({_ts(sel)}, "
                    f"{{ timeout: {action.get('timeout_ms', 15000)} }});"
                )
            elif a == "upload":
                L.append(f"{body}await page.setInputFiles({_ts(sel)}, {_ts(action.get('file', ''))});")
        exp = step.get("expect_text")
        for t in (exp if isinstance(exp, list) else [exp] if exp else []):
            L.append(f"{body}await expect(page.locator('body')).toContainText({_ts(t)});")
        if step.get("expect_url"):
            L.append(f"{body}await expect(page).toHaveURL(new RegExp({_ts(step['expect_url'])}));")
        if step.get("screenshot"):
            L.append(f"{body}await page.screenshot({{ path: {_ts(step['screenshot'])} }});")

    elif kind == "publish":
        L.append(
            f"{body}await publish({_ts(step['resource'])}, {_ts(step['target'])}, "
            f"{_ts(step['payload'])}, {_ts({'key': step.get('key'), 'headers': step.get('headers') or {}})}, ctx);"
        )

    elif kind == "await_message":
        match = {k: step[k] for k in ("match_contains", "match_json_path") if k in step}
        L.append(
            f"{body}const {v} = await awaitMessage({_ts(step['resource'])}, "
            f"{_ts(step['target'])}, {_ts(match)}, {step['timeout_ms']}, "
            f"{_ts({'from_beginning': step.get('from_beginning', True), 'min_count': step.get('min_count', 1)})}, ctx);"
        )
        L.append(f"{body}expect({v}.matched, 'no matching message observed').toBe(true);")
        L += _saves(step, v, body)

    elif kind == "await_blob":
        checks = {k: step[k] for k in ("name_pattern", "min_size_bytes", "content_contains")
                  if k in step}
        L.append(
            f"{body}const {v} = await awaitBlob({_ts(step['resource'])}, "
            f"{_ts(step['container'])}, {_ts(checks)}, {step['timeout_ms']}, ctx);"
        )
        L.append(f"{body}expect({v}.found, 'no matching blob observed').toBe(true);")
        L += _saves(step, v, body)

    elif kind == "upload_blob":
        payload = {
            "content": step.get("content"),
            "content_file": step.get("content_file"),
            "content_type": step.get("content_type"),
        }
        L.append(
            f"{body}await uploadBlob({_ts(step['resource'])}, {_ts(step['container'])}, "
            f"{_ts(step['blob_name'])}, {_ts(payload)}, ctx);"
        )

    elif kind == "sleep":
        L.append(f"{body}await new Promise((r) => setTimeout(r, {step['duration_ms']}));")

    L.append("    });")
    return L


def emit_journey(journey: dict[str, Any], inventory: dict[str, Any]) -> str:
    res = _resource_map(inventory)
    jid = journey["id"]
    needs_page = any(s.get("kind") == "browser" for s in journey["steps"])

    lines = [HEADER.format(jid=jid)]
    lines.append("import { test, expect } from '@playwright/test';")
    lines.append(
        "import { http, awaitHttp, publish, awaitMessage, awaitBlob, uploadBlob, "
        "jsonPath, newContext } from '../support/harness';"
    )
    lines.append("")
    src = journey.get("source") or {}
    lines.append(f"// Source: {json.dumps(src, sort_keys=True)}")
    if journey.get("description"):
        lines.append(f"// {journey['description']}")
    lines.append("")

    tags = journey.get("tags") or []
    title = journey["title"] + ("".join(f" @{t}" for t in sorted(tags)) if tags else "")
    sig = "async ({ page }) => {" if needs_page else "async () => {"
    lines.append(f"test({_ts(title)}, {sig}")
    lines.append("  const ctx = newContext();")
    lines.append("  await test.step('journey', async () => {")
    for i, step in enumerate(journey["steps"]):
        lines.extend(emit_step(step, i, res))
    lines.append("  });")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def emit_resource_table(inventory: dict[str, Any]) -> str:
    """One generated module holding every resource's connection detail, so the
    specs stay free of URLs and broker addresses."""
    table = {}
    for r in inventory.get("resources", []):
        table[r["id"]] = {
            "id": r["id"],
            "kind": r.get("kind"),
            "name": r.get("name"),
            "baseUrl": r.get("base_url"),
            "hostPort": r.get("host_port"),
            "image": r.get("image"),
        }
    return (
        "// GENERATED by e2e-harness. Do not edit.\n"
        "// Regenerate with: e2e build\n\n"
        "export type ResourceInfo = {\n"
        "  id: string;\n  kind: string;\n  name: string;\n"
        "  baseUrl?: string | null;\n  hostPort?: number | null;\n"
        "  image?: string | null;\n};\n\n"
        "export const RESOURCES: Record<string, ResourceInfo> = "
        + json.dumps(table, indent=2, sort_keys=True)
        + " as unknown as Record<string, ResourceInfo>;\n\n"
        "export function resource(id: string): ResourceInfo {\n"
        "  const r = RESOURCES[id];\n"
        "  if (!r) throw new Error(\n"
        "    `Unknown resource '${id}'. Run 'e2e discover' then 'e2e build'.`\n"
        "  );\n"
        "  return r;\n"
        "}\n"
    )


def build(journeys_doc: dict[str, Any], inventory: dict[str, Any]) -> dict[str, str]:
    """Return {relative_path: file_contents}. Caller writes them."""
    files: dict[str, str] = {"support/resources.ts": emit_resource_table(inventory)}
    for j in journeys_doc.get("journeys", []):
        files[f"generated/{j['id']}.spec.ts"] = emit_journey(j, inventory)
    return files
